name = "hybrid_app_ada"
description = "Hybrid DDD/Clean/Hexagonal architecture greeter application in Ada 2022"
version = "1.0.0"
authors = ["Michael Gardner"]
maintainers = ["Michael Gardner <mike@abitofhelp.com>"]
maintainers-logins = ["abitofhelp"]
licenses = "BSD-3-Clause"
website = "https://github.com/abitofhelp/hybrid_app_ada"
tags = ["hexagonal", "ddd", "clean", "functional", "monad", "example"]

executables = ["greeter"]

[build-switches]
"*".Ada_Version = "Ada2022"
"*".Style_Checks = "yes"

[[depends-on]]
functional = "^2.1.1"

[environment]

[[depends-on]]
gnatcov = "^22.0.1"

[[pins]]
functional = { path = '../functional' }
